# Generated by Django 5.2.2 on 2025-08-14 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_user_id', models.CharField(max_length=64, unique=True)),
                ('preferred_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=32)),
                ('usertype', models.CharField(blank=True, max_length=64)),
                ('emp_or_std_id', models.CharField(blank=True, max_length=64)),
                ('role', models.CharField(blank=True, max_length=128)),
                ('role_short', models.CharField(blank=True, max_length=64)),
                ('role_id', models.CharField(blank=True, max_length=64)),
                ('photo_local', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
