# Generated by Django 5.2.2 on 2025-08-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaluserprofile',
            name='photo_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
